- .travis.yml
- package.json
When running CI/CD run only install and build, source code is already there so no need to generate it.
> Fix release by using correct script and run only install

- .github/worflows/releaser.yml
Since heroku no longer supports free tier we should move away from our old bot to the new action we've created https://github.com/RedHatInsights/frontend-releaser. All secret tokens has been added.
> Use new releaser action

- packages/integrations/index.ts
- packages/notifications/index.ts
- src/main/resources/typescript-axios-webpack-module-federation/index.mustache
For [RHCLOUD-31533](https://issues.redhat.com/browse/RHCLOUD-31533), part of [JS-Client overhaul](https://issues.redhat.com/browse/RHCLOUD-26625)
> Shorten api names to prevent confusion

- packages/integrations/README.md
- packages/integrations/doc/README.md
- packages/notifications/README.md
- packages/notifications/doc/README.md
For [RHCLOUD-28020](https://issues.redhat.com/browse/RHCLOUD-28020). Currently only updating the new generator clients (integrations and notifications) as the usage change only applies to them. As more clients get converted, their READMEs can be updated to match these.
> docs: update usage in README for new-gen clients

- .github/actions/release/action.yaml
- nx.json
- package-lock.json
- package.json
- packages/build-utils/executors.json
- packages/build-utils/package.json
- packages/build-utils/src/executors/old-builder/old-executor.spec.ts
- packages/build-utils/src/executors/old-builder/old-executor.ts
- packages/build-utils/src/executors/old-builder/schema.d.ts
- packages/build-utils/src/executors/old-builder/schema.json
- packages/config-manager/project.json
- packages/entitlements/project.json
- packages/host-inventory/project.json
- packages/insights/project.json
- packages/integrations/project.json
- packages/notifications/project.json
- packages/patch/project.json
- packages/policies/project.json
- packages/quickstarts/project.json
- packages/rbac/project.json
- packages/remediations/project.json
- packages/sources/project.json
- packages/topological-inventory/project.json
- packages/vulnerabilities/project.json
Since [GH actions](https://github.com/RedHatInsights/javascript-clients/actions/runs/8751031768/job/24015881192#step:3:376) doesn't want to use things like `mkdir`, we're writing a custom executor using `fs` and `fs-extra` instead to get our output matching our old clients.
> Add new exec for old output

- packages/shared/README.md
- packages/shared/project.json
Seems like there were [some issues](https://github.com/RedHatInsights/javascript-clients/actions/runs/8920058635/job/24497448706) publishing the shared package because of an executor error? Need this package published consumption in integrations and notifications clients. If this release fails, I can tweak the executor to fix the above error.
> Publish javascript-shared-clients package

- package-lock.json
- packages/compliance/package.json
Noticed the shared package was missing from Compliance client
Make a new compliance release please
> fix: add shared package to compliance

- packages/compliance/README.md
- packages/compliance/project.json
This _should_ fix the issue. Previously after a successful merge before, another GH action run from nacho-bot for compliance-client would run with incorrect tags for other clients causing a release step failure.
> Update commitMessageFormat for nacho-bot

- postProcess.sh
For [RHCLOUD-32914](https://issues.redhat.com/browse/RHCLOUD-32914). Turns out the issue is in the `postProcess.sh` file specifically for OSX that runs for all our generators 🥴  unblocks https://github.com/RedHatInsights/javascript-clients/pull/262
> Prevent plural deletion when generating on OSX

- package-lock.json
- packages/rbac/package.json
`rbac-client` was using an old version of js-clients-shared with an out of date Axios version for [RHCLOUD-34295](https://issues.redhat.com/browse/RHCLOUD-34295).
> Update javascript-clients-shared version in rbac-client

- .github/workflows/sync-apis.yml
Updating to use the correct version for `actions/setup-java`.
Fear the pacman!  :v    :ghost:
> Using correct version for actions/setup-java

- .github/workflows/sync-apis.yml
Update client generation cronjob to only run once a day and use the latest version of PR creation action.
> Update client generation cronjob

- packages/compliance/README.md
- packages/config-manager/README.md
We had some release [failures](https://github.com/RedHatInsights/javascript-clients/actions/runs/11738666735/job/32701722152) that resulted in version bumps, but not actual package releases. This caused NX to have a cached GH version that didn't actually exist. I've deleted the tags in GH which should allow these two packages to create their tags properly and then release on NPM.
> Update docs for compliance and config-manager-client

- packages/shared/utils.ts
- src/main/resources/typescript-axios-webpack-module-federation/api.mustache
- src/main/resources/typescript-axios-webpack-module-federation/coreApi.mustache
- src/main/resources/typescript-axios-webpack-module-federation/endpointImports.mustache
- src/main/resources/typescript-axios-webpack-module-federation/endpointTypes.mustache
- src/main/resources/typescript-axios-webpack-module-federation/index.mustache
~~**Still a WIP - we need to address the actual return object type in `AxiosResponse` - right now it is just `unknown` - but it should be what the OpenAPI spec specifies.**~~ 
Update: I was able to get the return type to match the OpenAPI spec now too.
This was not a trivial change as we are trying to use generics for all the clients. There are still some improvements to be had we will look into later. I'm open to making whatever export/data structure changes we see fit.
To test:
1. Build generator `npm run build:generator`
1. Build javascript-client-shared `npm run nx -- run @redhat-cloud-services/javascript-clients-shared:build --skip-nx-cache`
1. Generate host-inventory `npm run nx -- run @redhat-cloud-services/host-inventory-client:generate --skip-nx-cache`
1. In host-inventory - …
> Update shared API factory library return type to be AxiosResponse

- packages/compliance/README.md
- packages/entitlements/README.md
- packages/host-inventory/README.md
- packages/insights/README.md
- packages/integrations/README.md
- packages/notifications/README.md
- packages/patch/README.md
- packages/policies/README.md
- packages/quickstarts/README.md
- packages/rbac/README.md
- packages/remediations/README.md
- packages/shared/README.md
- packages/sources/README.md
- packages/topological-inventory/README.md
- utils/nx-base/README.md
~~Using this as a first-pass for the new `api.ts` usage README. Once this gets merged, I'll open another PR for the rest of the clients' READMEs as they'll need this usage update too.~~ 
Updated READMEs for all clients (minus vulnerabilities as it still is on the old generator) with the new `api.ts` usage.
> Update compliance-client README with new api usage

- packages/integrations/tests/integration/integrations.v1.integration.test.ts
- packages/integrations/v2/tests/integration/integrations.v2.integration.test.ts
In some cases the server is returning a 404 status code, which causes test failures. Until we can identify and properly address these situations, let's skip the associated tests.
> Handle failures due to 404 status codes

- package-lock.json
- packages/rbac/project.json
- packages/rbac/types/index.ts
The `v2` spec for rbac is no longer valid as it was renamed. This PR also updates the client with the new spec changes.
> Update rbac-client v2 spec name

- packages/quickstarts/package.json
We will be making breaking changes to the directory structure of the clients by switching to the new builder (which supports both commonjs and esm builds).
Using this PR to test if nacho bot will create a github tag and release for us when using `!` after `feat`.
> feat!: release version 3.0.0 of quickstarts in prep for new builder

- package-lock.json
- packages/quickstarts/package.json
- packages/quickstarts/project.json
Part of https://issues.redhat.com/browse/RHCLOUD-32282 (convert clients to the new builder and support esm and cjs builds).
> feat!: Update quickstarts to use new builder

- packages/notifications/jest.config.ts
- packages/notifications/jest.integration.v1.config.ts
- packages/notifications/jest.integration.v2.config.ts
- packages/notifications/project.json
- packages/notifications/tests/integration/notifications.v1.integration.test.ts
- packages/notifications/tsconfig.integration.v1.spec.json
- packages/notifications/tsconfig.integration.v2.spec.json
- packages/notifications/v2/tests/integration/notifications.v2.integration.test.ts
Depends on https://github.com/RedHatInsights/javascript-clients/pull/341.
Establishes test coverage for Notifications API v1 and v2.
> notifications api client tests

- packages/integrations/tests/integration/integrations.v1.integration.test.ts
Related to RHCLOUD-37161
We have some tests that consume out-of-date endpoints (removed from the spec but not the generated client). This PR deletes the associated tests.
> RHCLOUD-37159: Remove tests of non-public Integrations v1 endpoints

- packages/notifications/v2/tests/integration/notifications.v2.integration.test.ts
Replaces existing, manually-crafted tests with new ones generated from the openapi spec for notifications api v2.
> RHCLOUD-37068: Generated Notifications V2 Tests

- bin/serve.sh
When `jq` isn't installed, the serve.sh script fails quietly. Make it fail loudly and explicitly.
> RHCLOUD-41072: Error handling when jq is missing
