RedHatInsights/javascript-clients

packages/approval/package.json
=> Update openapi spec file name

.travis.yml
Fixes missing env variable in release script.
=> Use specific node version number.

packages/config-manager/tsconfig.spec.json, packages/entitlements/tsconfig.spec.json, packages/host-inventory/tsconfig.spec.json, packages/insights/tsconfig.spec.json, packages/integrations/tsconfig.spec.json, packages/notifications/tsconfig.spec.json, packages/patch/tsconfig.spec.json, packages/policies/tsconfig.spec.json, packages/quickstarts/tsconfig.spec.json, packages/rbac/tsconfig.spec.json, packages/remediations/jest.config.js, packages/remediations/tsconfig.spec.json, packages/sources/tsconfig.spec.json, packages/topological-inventory/tsconfig.spec.json, packages/vulnerabilities/tsconfig.spec.json
Hoping this fixes the release issue for https://github.com/RedHatInsights/javascript-clients/actions/runs/8465320606
=> fix: add missing spec files to each client

postProcess.sh
Fix for [RHCLOUD-31683](https://issues.redhat.com/browse/RHCLOUD-31683)
=> fix: prevent osx from hanging during client generation

utils/nx-base/project.json
Small options update for project config template for `npm run create-client`
=> Update project.json for create-client

packages/shared/README.md
Need a version bump for publishing
=> Update shared docs for publishing

packages/compliance/README.md, packages/integrations/README.md, packages/notifications/README.md
Previous tags deleted, trying to get new versions released
=> Get new releases of compliance, integrations, and notifications

package-lock.json, packages/compliance/package.json, packages/integrations/package.json, packages/notifications/package.json, packages/rbac/package.json, packages/shared/package.json
See https://issues.redhat.com/browse/RHCLOUD-32394
=> RHCLOUD-32394: Update axios to latest for able clients

.github/workflows/ci.yml
For [RHCLOUD-32724](https://issues.redhat.com/browse/RHCLOUD-32724)
=> Update GH actions to use node 20

.github/actions/cypress-cache/action.yaml, .github/actions/lint/action.yaml, .github/actions/node-cache/action.yaml, .github/actions/release/action.yaml, .github/actions/test-unit/action.yaml, .github/actions/webpack-cache/action.yaml, .github/workflows/ci.yml
Pt. 2 of https://github.com/RedHatInsights/javascript-clients/pull/278
=> Update remaining action caches to use node 20

nx.json
Checking to see if this fixes failing [CI problems](https://github.com/RedHatInsights/javascript-clients/actions/runs/11919576162/job/33219659162?pr=326) because we 'ran out' of credits
=> Disable nx cloud

packages/integrations/jest.integration.v2.config.ts, packages/integrations/project.json, packages/integrations/tsconfig.integration.v2.spec.json, packages/integrations/v2/tests/integration/integrations.v2.integration.test.ts
Depends on https://github.com/RedHatInsights/javascript-clients/pull/336
15 tests for the integrations API V2. Essentially a copy of the V1 tests with modifications.
=> integrations v2 tests

package-lock.json, packages/compliance/package.json, packages/compliance/project.json
Jira:  https://issues.redhat.com/browse/RHCLOUD-32282
=> feat!: Update compliance to use new builder

packages/entitlements/package.json, packages/entitlements/project.json
=> feat!: Update entitlements to use new builder

packages/notifications/package.json, packages/notifications/project.json
=> feat!: Update notifications to use new builder

packages/host-inventory/package.json, packages/host-inventory/project.json
=> feat!: Update host-inventory to use new builder

packages/patch/package.json, packages/patch/project.json
=> feat!: Update patch to use new builder

packages/rbac/package.json, packages/rbac/project.json
=> feat!: Update rbac-client to use new builder

packages/remediations/package.json, packages/remediations/project.json
=> feat!: Update remediations-client to use new builder

packages/sources/package.json, packages/sources/project.json
=> feat!: Update sources-client to use new builder

packages/topological-inventory/package.json, packages/topological-inventory/project.json
=> feat!: Update topological-inventory-client to use new builder

packages/vulnerabilities/package.json, packages/vulnerabilities/project.json
=> feat!: Update vulnerabilities-client to use new builder

utils/nx-base/project.json
=> Updating nx-base to use the new builder in nx-base

package-lock.json, packages/shared/package.json, packages/shared/project.json
=> feat!: Update javascript-clients-shared to use new esm builder

packages/host-inventory/ApiHostDeleteHostsByFilter/index.ts, packages/host-inventory/ApiHostGetHostList/index.ts, packages/host-inventory/ApiTagGetTags/index.ts, packages/host-inventory/types/index.ts
update host-inventory-client to accept new Hosts 'systemType' param
=> feat(RHINENG-18834): update host-inventory-client to accept new Hosts 'systemType' param
